### ISSUE TITLE
[SUGGESTION] 🪄Add new commands and abilities to VelocityVanish

### ISSUE THREAD

**Issue by User4716** [Syrent/SayanVanish#154]
## Suggestions:

Here I have a couple of suggestions that would make this plugin better and more advanced. Some of these commands/features might already be in this plugin, but I decided to mention them anyways to be sure that this plugin is Perfect 👌

Remember that I am just giving you suggestions, you do not have to do any of these. I'm just giving ideas out of my head :D
Also, I put an 🪄 emoji to the suggestions that I think are nice to have, but are not 100% needed.

‎ 

## ⭐️**New commands**

-  ~~`/velocityvanish fakejoin <player>` Broadcast a fake join message of specified player. Also you can fakejoin any user even if 
    they are not online. _[🪄And this will create a fake player to the TAB-list and Serverlist if enabled in the config.]_~~ **(Added since VelocityVanish 3.19.1-beta.10)**

- ~~`/velocityvanish fakequit <player>` Broadcast a fake quit message of specified player. Also you can fakequit any user even if 
    they are not online _[🪄This will remove the fake player from the TAB-list and Serverlist if enabled in the config.]_~~
 **(Added since VelocityVanish 3.19.1-beta.10)**
-  ~~`/silentvanish <player> <on/off>` Toggles silentvanish for the specified player. Silentvanish doesn't broadcast any fake leave 
    message or join message.~~ **(Added since VelocityVanish 3.19.1-beta.10)**

-  `/velocityvanish joinvanish <player>` Toggles the "vanish on join feature" on/off for the specified player.

-  🪄 ~~`/velocityvanish vanishlevel <level> <player>` Sets the "vanish use level" that the player will use next time when /vanish   
   is executed. If a player is already in vanish it will change immediately. (Vanish use level is "velocityvanish.level.[level]")~~ **(Added since VelocityVanish 3.19.1-beta.10)**

-  🪄 ~~`/velocityvanish seelevel <level> <player>` Sets the "vanish see level" that the player will use. 
  (Vanish see level is "velocityvanish.see.[level]")~~ **(Added since VelocityVanish 3.19.1-beta.10)**

- `/velocityvanish pickup` Toggle picking up items while in vanish

- `/velocityvanish chat` Toggle chat usage while in vanish so that you don't accidentally type a message 
   (Commands are allowed to be run)

‎ 

## 🛠️**New features**
- ~~Enable night vision when vanished (If not already implemented)~~ **(Already Implemented)**

- Right-clicking doors will teleport you through them. (If you don't want to make noises while near a player)

- 🪄 You can now **enable/disable** all these different things that will be applied when entering vanish. You could essentially choose "what parts of the server you're invisible and visible in."

(These can be configured in the settings.yml file)

>   Hunger, mobs/players pushing you, night vision, mobs from targeting you, pressure plates and tripwires from activating,  hide from TAB-list, hide from serverlist, hide from commands, hide player skin armor and hand items, drip leaf activating, 
>   turtle_egg_breaking, player/entity kill messages, chunk loading, raid activating, visible in spectator menu, achievement 
>   messages, disable chat, and particles produced by you.

- Custom commands could be configured to be run when **entering/leaving** vanish, or **leaving/joining the server while vanished.** 
_🪄You could also maybe specify different actions for different vanish levels so that the custom commands can be different for each vanish level._

‎ 
- 🪄 You can now configure for example that will "silent container open" be enabled if you use Vanish level 1. 
  Or will you be able to load chunks if you use vanish level 2 
  These are all the things that you can **enable/disable** for each Vanish level separately:

   'block_break' 'block_place' 'item_pickup' 'hunger' 'night_vision' 'mob_target' 'entity_push' 
   'redstone_activate' 'fly' 'hide_tab' 'hide_serverlist' 'hide_from_commands' 'hide_player' 'activate_drip_leaf' 'break_turtle_egg' 
   'activate_raid' 'door_teleport' 'see_as_spectator' 'keep_vanish_on_rejoin' 'invincible' 'pickup_items' 'use_chat' 'hit_players' 
   'hit_entities' 'hide_death_message' 'hide_kill_message' 'load_chunks' 'particles' 'visible_in_spectator_menu'  
   'achievement_messages' 'fake_leave_message' 'fake_join_message' and 'interact'

>    Yes, this is a lot, and if you don't think we need this then just ignore this, but at least I've written this suggestion so you won't run out of things to do :)

‎ 
‎ 

## 🛡️**New permissions**
- ~~`velocityvanish.command.vanish.others` Vanishing other players is not allowed with "velocityvanish.command.vanish" 
   permission anymore, you will need this permission now.~~ **(Added since VelocityVanish 3.19.1-beta.10)**
- ~~`velocityvanish.see.[level]` There is already the "vanish use level" permission, but no "vanish see level" permission (I think)~~ **(Added since VelocityVanish 3.19.1-beta.10)**
- ~~`velocityvanish.command.fakejoin` Used for command "/velocityvanish fakejoin"~~ **(Added since VelocityVanish 3.19.1-beta.10)**
- ~~`velocityvanish.command.fakequit` Used for command "/velocityvanish fakequit"~~ **(Added since VelocityVanish 3.19.1-beta.10)**
- ~~`velocityvanish.command.joinvanish` Used for command "/velocityvanish joinvanish"~~ **(Added since VelocityVanish 3.19.1-beta.10)**
- ~~`velocityvanish.command.vanishlevel` Used for command "/velocityvanish vanishlevel"~~ **(Added since VelocityVanish 3.19.1-beta.10)**
- `velocityvanish.command.seelevel` Used for command "/velocityvanish joinvanish"
- `velocityvanish.command.pickup` Used for command "/velocityvanish pickup"
- `velocityvanish.command.chat` Used for command "/velocityvanish chat"

‎ 

### And that seems to be all of my ideas there! 😀
**Keep in mind that I'm just giving you ideas for your plugin, do not feel pressure to make any of these. 
Consider making some of these features I suggested, I would really hope to see them one day in this plugin!
Anyways, I love your work, your plugins make my server so much better! Thank you 😊💖**

### Checklist

- [X] I am running latest version of the plugin on both Velocity and Spigot
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them

> v1.5

**Comment by Syrent** [comment]
Thanks for your feature suggestions, I really appreciate them!

Right now, I'm in the middle of my final exams, so I won't be able to work on these features immediately. However, my top priority at the moment is SayanEggwars plugin, which you can check out on our Discord.

Once I'm done with the plugin, I'll definitely work on adding these features. I've also been planning some changes to the codebase for a while now, so when I combine those changes with your suggestions, we'll have a new and improved version 4.0.0 of the plugin.

Thank you again for your awesome suggestions!

**Comment by User4716** [comment]
oOOOhhh Cool!
Hope you exams go well. I understand that you are not able to work on these features immediately.
And SayanEggwars.. sounds cool, I'll have a look into it. 

Personally, I think that if I added Bedwars, Skywars, or Eggwars to my server it would not be a popular minigame. All these gamemodes are in Hypixel (I don't know about Eggwars, but it's really similar to Bedwars.) So I think the games would not be popular because Hypixel has more players etc.
But if the Eggwars game would be unique, it could be interesting to my players! Just like if I added lucky blocks to my SkyWars maps.

I am really looking forward to the 4.0.0 updates, it sounds like Minecraft 2.0 to me. But take your time on everything! 😉
Peace

**Comment by fkydcdf** [comment]
@Syrent 
can you add able to change vanish join and quit messages and able to disable these in config file.  and able to change placeholder %velocityvanish_vanished% messages

**Comment by Syrent** [comment]
[Updated] Added some of the features in 3.19.1-beta.10 (Part 1)

**Comment by Syrent** [comment]
Project has been completely recoded. so this issue is no longer applicable to plugin.
I'd appreciate if you rewrite this issue with new version.
