### ISSUE TITLE
Whisper Vanished Players

### ISSUE THREAD

**Issue by teoWei** [Syrent/SayanVanish#156]
### Server backend version

paper-1.19.4-524.jar

### Server Velocity version

VelocityVanish.v3.18.1.jar

### VelocityVanish version

3.18.1

### Describe the bug

You can whisper to someone in vanish.

### Expected behavior

You aren't allowed to whisper someone in vanish.

### Steps to reproduce

Step 1: Have 2 players on the server. One in vanish. The other unvanished.
Step 2: Have the unvanished player whisper you.
Step 3: They will observe that the vanished player appears in the tab command completion thing.

### Checklist

- [X] I am running latest version of the plugin on both Velocity and Spigot
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them

**Comment by Syrent** [comment]
Hi, Please provide the following information:
- Your settings.yml file
- A video showing the problem

**Comment by SadBluez** [comment]
settings.yml :
```
#
# Full wiki is available at https://github.com/Syrent/VelocityVanish/wiki
#
config_version: 5
default_language: en_US
show_dependency_suggestions: true
# NOT RECOMMENDED, Legacy code support is extremely discouraged. It affects performance, and it does not contain the new minecraft chat features.
support_legacy_color_codes: false
# If you are the first player to join the server, the Vanish data may not be synchronized correctly,
# and you will not be in vanish mode. This option allows you to enter vanish mode if you have operator privileges
# or the "velocityvanish.action.vanish.force" permission. If you were not previously in vanish mode,
# it will unvanish you after a few seconds.
force_vanish_if_first: true

bstats: true
# Leave sounds blank to disable them
# Example: command: ""
sounds:
  command: ENTITY_EXPERIENCE_ORB_PICKUP
  vanish: ENTITY_EXPERIENCE_ORB_PICKUP
  unvanish: ENTITY_EXPERIENCE_ORB_PICKUP
vanish:
  # Show players actionbar when they are vanished
  actionbar: true
  # Remember vanish data after switch servers?
  # Note: Need Velocity as proxy server
  remember: true
  # Should we change player type to spectator in tablist for players who have permission to see vanished players?
  # Note: Requires ProtocolLib
  see_as_spectator: true
  # Should vanished players be protected from all damage sources?
  invincible: true
  # Prevent vanished players from pickup items
  prevent_pickup: true
  # Note: Not working when some ProCosmetics cosmetics are enabled!
  silent_open_container: true
  prevent:
    block_break: false
    block_place: false
    interact: false
```

Video of problem : https://youtu.be/9Ybhc_7HwuY

I would also like to add on to this issue that vanished player still appear on the Server Listing, and when reloading, it broadcasts a join message of everyone in the server and vanished player doesn't stay vanished after reload.

**Comment by Syrent** [comment]
Do you use any message plugins like EssentialsX or VentureChat?

**Comment by Syrent** [comment]
This issue was inactive for a long time, the project is recoded so i hope the problem is solved.
