### ISSUE TITLE
Vanish on join toggles off after ~1 second

### ISSUE THREAD

**Issue by Kaassss** [Syrent/SayanVanish#307]
### Server backend version

1.20.4

### Server backend Java version

21

### Server Velocity version

3.3.0-b378

### Server Velocity Java version

21

### VelocityVanish version

3.27.3-build.60-901daad

### Describe the bug

When leaving the server OUT of vanish, and then rejoin, the following happens:
- I am IN vanish (also on TAB) for +- 1 sec and get the corresponding Night Vision Effect (This is good as I have the `velocityvanish.action.vanish.onjoin` permission.)
  - During this time, using `/papi parse me %velocityvanish_vanished%` returns `true`
- Then, after the second, the vanish turns (half-)off
  - The night vision stays and you are physically not visible for players
  - I become visible on TAB without the [V] (The [V] was added by the owner to indicate being vanished on TAB)
  - Using `/papi parse me %velocityvanish_vanished%` returns `false`
  - There is NO message in chat saying something about it being disabled, but when I use `/v(anish)` it does get enabled (so it must have been disabled/off?).

The same occurs when I switch between servers in the same network, all with the same VelocityVanish settings; where I am vanished shortly after which it gets disabled.

(When leaving the server out of vanish and rejoining, I am in vanish correctly.)

### Expected behavior

When a player has the `velocityvanish.action.vanish.onjoin` permission, that whenever they join the server, they stay inside vanish until they themselves decide to toggle it off.

### Steps to reproduce

Step 1 - Have the `velocityvanish.action.vanish.onjoin` permission _(and other standard vanish permissions)_
Step 2 - Make sure you are not in vanish
Step 3 - Leave the server
Step 4 - Rejoin the server (time before rejoining does not matter)
Step 5 - Check TAB/PlaceholerAPI to see you are vanished for about a second, after which it turns off

### VelocityVanish's configuration file

```# Full wiki is available at https://github.com/Syrent/VelocityVanish/wiki
config_version: 9
default_language: en_US
show_dependency_suggestions: true

# IMPORTANT: Legacy code support is strongly discouraged. It adversely affects performance and lacks new Minecraft chat features.
support_legacy_color_codes: false

# If you're the first player to join the server, Vanish data may not synchronize correctly,
# and you may not enter vanish mode. With this option enabled, you can still enter vanish mode
# if you have operator privileges or the "velocityvanish.action.vanish.force" permission.
# If you weren't previously in vanish mode, you'll be unvanished after a few seconds.
force_vanish_if_first: true

bstats: true
# Leave sounds blank to disable them
# Example: command: ""
sounds:
  command: ENTITY_EXPERIENCE_ORB_PICKUP
  vanish: ENTITY_EXPERIENCE_ORB_PICKUP
  unvanish: ENTITY_EXPERIENCE_ORB_PICKUP
vanish:
  # Show players an actionbar when they are vanished
  actionbar: true
  # Remember vanish data after switching servers?
  # Note: Requires Velocity as a proxy server
  remember: true
  # Should we change player type to spectator in tablist for players who have permission to see vanished players?
  # Note: Requires ProtocolLib in versions lower than 1.19
  see_as_spectator: false
  # Should vanished players be protected from all damage sources?
  invincible: true
  # You can also achieve this by setting the fake join/leave message to blank in the language file
  fake_join_leave_message: true
  silent_open_container: true
  # Might cause incompatibility with some plugins like TAB and eGlow
  disable_collision: false
  prevent:
    pickup: true
    block_break: false
    block_place: false
    interact: false
    # Only works on PaperMC servers (Paper, Purpur, Pufferfish, etc...)
    advancement: true
hooks:
  essentials:
    enabled: false
    force_prevent_private_messages: false
  sunlight:
    enabled: false
  placeholderapi:
    enabled: true
  protocollib:
    enabled: true
  squaremap:
    enabled: true
  discordsrv:
    enabled: false
  cmi:
    enabled: false
```

### Plugins

On bungee: LuckPerms, TAB, VelocityControl, VelocityVanish
On spigot servers: LuckPerms, PlaceholderAPI, ProtocolLib, TAB-Bridge, VelocityControl, VelocityVanish

### Additional info

![image](https://github.com/Syrent/VelocityVanish/assets/56442163/3d0863e1-aa6e-4836-b473-141a21daaf59)

### Checklist

- [X] I am running the latest version of the plugin on both Velocity and Spigot
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I tried the plugin on a fresh server and it didn't work (Or it worked but I know exactly which plugin it's incompatible with)
- [ ] I ticked all of the boxes without actually reading them

**Comment by Syrent** [comment]
fixed in SayanVanish release candidate 1
