### ISSUE TITLE
[Request] Tablist option

### ISSUE THREAD

**Issue by t4ba** [Syrent/SayanVanish#316]
possible to add a option to vanish player show in the tablist ? 

with this we can vanish without getting noticed. like disabled join and leave messages. no one get know.

**Comment by Syrent** [comment]
it must hide you in tab, what plugin do you use for tablist?

**Comment by t4ba** [comment]
> it must hide you in tab, what plugin do you use for tablist?

it does show but im asking for a option to show players when they vanish
