### ISSUE TITLE
java.sql.SQLException: Connection is closed

### ISSUE THREAD

**Issue by fabianmakila** [Syrent/SayanVanish#318]
After running SayanVanish overnight in our network, every single one of our servers which had SayanVanish installed started printing this error.

[Paper error](https://pastes.dev/CXYw9PYcZM)

Even the proxy started printing the same error.

[Proxy error](https://pastes.dev/ut623oFqKY)

Every other plugin connected to the same database is working properly. SayanVanish is the only one that's throwing errors.

## Version information
SayanVanish `1.1.0-a148634`
Proxy (Velocity) `Velocity 3.3.0-SNAPSHOT (git-e60e2063-b399)`
Backend (Paper) `Paper version git-Paper-497 (MC: 1.20.4)`

**Comment by Syrent** [comment]
hey, try latest snapshot build
https://hangar.papermc.io/Syrent/SayanVanish/versions/1.1.2-SNAPSHOT-build.140

**Comment by fabianmakila** [comment]
That seems to have fixed the issue. I've been running the snapshot for a few days straight now and nothing has broken yet.
