### ISSUE TITLE
Add events on bungeecord

### ISSUE THREAD

**Issue by jehendeoff** [Syrent/SayanVanish#323]
I wanted to know when a player vanished in my plugin (on bungeecord) but I can't find any event, after looking at the code, it seems no events is triggered on bungeecord? (only on velocity) (I don't know kotlin, so I may be wrong)

Is it possible to implement some event at all ? (I wouldn't need pre- event, only post, to know when a player vanishes so I handle it correctly)

**Comment by Syrent** [comment]
hey, i'll implement bungeecord events in the next update (probably tomorrow)

**Comment by Syrent** [comment]
added in latest snapshot (1.2.0)
