### ISSUE TITLE
While in spectator mode disabling vanish player falls through world.

### ISSUE THREAD

**Issue by Technicolor-creamsicle** [Syrent/SayanVanish#325]
When a player is in spectator mode with vanish on and proceeds to disable vanish the player will continuously fall through the world and die from falling through the world until they disconnect and reconnect.

Server version: Folia for 1.20.4
Plugin version: 1.2.0

**Comment by Syrent** [comment]
fix in latest snapshot
https://hangar.papermc.io/Syrent/SayanVanish/versions/1.2.1-SNAPSHOT-build.150

**Comment by Syrent** [comment]
i'll close this issue, let me know if it happened again.
