### ISSUE TITLE
[Bungee] BungeeUserVanishEvent is never fired

### ISSUE THREAD

**Issue by jehendeoff** [Syrent/SayanVanish#327]
Hi again, your plugin's working great, but I found what I believe is a typo, in the file `sayanvanish-proxy/sayanvanish-proxy-bungeecord/src/main/kotlin/org/sayandev/sayanvanish/bungeecord/feature/features/FeatureSyncEvents.kt`

Both event ([line 31](https://github.com/Syrent/SayanVanish/blob/b11b1bf0436a3135830925d88551c198347683f7/sayanvanish-proxy/sayanvanish-proxy-bungeecord/src/main/kotlin/org/sayandev/sayanvanish/bungeecord/feature/features/FeatureSyncEvents.kt#L31) and [line 36](https://github.com/Syrent/SayanVanish/blob/b11b1bf0436a3135830925d88551c198347683f7/sayanvanish-proxy/sayanvanish-proxy-bungeecord/src/main/kotlin/org/sayandev/sayanvanish/bungeecord/feature/features/FeatureSyncEvents.kt#L36)) that are fired are the unvanish event, and the vanish event is never fired

*from what I can tell, this doesn't affect velocity, as [line 34](https://github.com/Syrent/SayanVanish/blob/b11b1bf0436a3135830925d88551c198347683f7/sayanvanish-proxy/sayanvanish-proxy-velocity/src/main/kotlin/org/sayandev/sayanvanish/velocity/feature/features/FeatureSyncEvents.kt#L34) in the velocity file is the vanishEvent*

**Comment by Syrent** [comment]
hey, try latest snapshot:
https://hangar.papermc.io/Syrent/SayanVanish/versions/1.3.1-SNAPSHOT-build.163

**Comment by jehendeoff** [comment]
works great, thank you
