### ISSUE TITLE
PAPI support

### ISSUE THREAD

**Issue by BalazsManus** [Syrent/SayanVanish#329]
It would be nice to use PlaceholderAPI with fake join/leave messages
![image](https://github.com/user-attachments/assets/9c0b8e2b-65f8-47b0-86f2-f6f0bbb0c123)

**Comment by Syrent** [comment]
try this build:
https://hangar.papermc.io/Syrent/SayanVanish/versions/1.4.1-SNAPSHOT-build.169

**Note:** Your placeholders must not contain legacy color codes (`&` or `§`). you have to use [MiniMessage](https://docs.advntr.dev/minimessage/index.html) format.
