### ISSUE TITLE
[Paper 1.21] Cannot find kotlin-reflect on classpath

### ISSUE THREAD

**Issue by HaHaWTH** [Syrent/SayanVanish#330]
**Server Implementation:**
Paper 1.21 build 107

**SayanVanish version:**
1.4.1-b169

**Reproduce steps:**
1. Install SayanVanish 1.4.1-b169 on Paper server
2. Start the server
3. Error occurred while enabling SayanVanish

**Error logs:**
https://mclo.gs/Oluxmrh

**Comment by Syrent** [comment]
i'm unable to replicate the issue on my local server
my server log: https://paste.sayandev.org/ZUtfdMakHk
can you send me the full server log?

**Comment by HaHaWTH** [comment]
After testing on the latest version Paper & Purpur, it is caused by the server software.
Now closed, thanks a lot!
