### ISSUE TITLE
Integrate MiniPlaceholders

### ISSUE THREAD

**Issue by JuraRusan** [Syrent/SayanVanish#335]
Hello! I would like to request the possibility of integrating with [MiniPlaceholders](https://modrinth.com/plugin/miniplaceholders), if it's feasible. This became relevant after a discussion with the developers of the [Velocitab plugin](https://william278.net/project/velocitab), where it was noticed that even though a player is hidden, they are still counted on the server, creating the impression of an administrator's presence. Integration could significantly improve this aspect.

Thanks in advance!

The users are standing face to face. gmgame (default user) and prestig9110 (admin) - vanish mode is enabled.
![image](https://github.com/user-attachments/assets/34d0bea1-b4f2-4c3e-bc60-92824f60e05c)
![image](https://github.com/user-attachments/assets/c5d6a266-fa84-46b6-b5f5-ce994a9301a6)

**Comment by Syrent** [comment]
try this version:
https://hangar.papermc.io/Syrent/SayanVanish/versions/1.5.0-SNAPSHOT-build.184

placeholder expansion and keys are the same as PlaceholderAPI (e.g: `<sayanvanish_online_total>`)

**Comment by JuraRusan** [comment]
Oh, that was quick! Thank you so much! It’s working perfectly on the test server (I’ll check it later on the live server with players).
