### ISSUE TITLE
[Request] Folia 1.21.1 Support

### ISSUE THREAD

**Issue by Aruvelut-123** [Syrent/SayanVanish#342]
I know it supports folia, but my server is folia 1.21.1 and the plugin is not supported.
Please support it so that i can use

**Comment by Syrent** [comment]
What's the error?

**Comment by Aruvelut-123** [comment]
Oh it's my bad i see no folia label on modrinth page so i think it not support.
Sorry to trouble you.
And i guess you should update the modrinth page to add folia label to make sure others won't think it will not work.
Anyway, thanks for reply me.
