### ISSUE TITLE
About entering the server

### ISSUE THREAD

**Issue by MeowStarrySea** [Syrent/SayanVanish#344]
This plugin is being applied to my server, but I am currently encountering some problems. When I use the permission "sayanvanish.*" to enter the server, I will not receive the server broadcast. But it will not let me enter the server invisibly. So I can only use "sayanvanish.action.vanish.onjoin", but in this way I will receive the broadcast when I enter the server. So what should I do to enter the server invisibly and not receive the server broadcast?

**Comment by Syrent** [comment]
hey, what version of SayanVanish do you use? (Please use `/ver SayanVanish` and send the full version name)

**Comment by Syrent** [comment]
this issue been open for a month with no response, i'll close the issue. re-open it if you still have the issue with latest snapshot
