### ISSUE TITLE
PLUGIN IS BROKEN???

### ISSUE THREAD

**Issue by HonzasikCZ** [Syrent/SayanVanish#348]
VERSION: Purpur 1.21.1-2328-d49ca07 (MC: 1.21.1)

PLUGIN VERSION: 1.5.1-SNAPSHOT-build.202-cd60777

PLUGINS: LibreLogin, AntiWorldDownloader, AxInventoryRestore, AxTrade, CataMines, CMI, CMILib, CommandWhitelist, EntityClearer, ExcellentCrates, FastAsyncWorldEdit, HostifyMonitor, ItemEdit, ItemTag, LiteBans, LuckPerms, MiniMOTD, nightcore, packetevents, PinataParty, PlaceholderAPI, ProtocolLib, PvPManager, PyrsCore, PyrsPlots, SayanVanish, Shopkeepers, SkinsRestorer, Skript, Sonar, TAB, ViaBackwards, ViaVersion, Votifier, Vulcan, WorldGuard

Hi...yesterday I put a plugin on one server but I noticed that a lot of things either work weird or don't even work... for example **sneak_toggle_gamemode** doesn't work at all even if it's turned on, **silent_container** doesn't work either (the game mode somehow switches it but the player hears it anyway), **actionbar** and also **fake_message**..no idea what else doesn't work but this is the first thing I noticed...

I hope there will be some good solution and thanks for reading! :)

As for the previous report..unfortunately I am no longer on the server so I could not resolve it further.

**Comment by HonzasikCZ** [comment]
So...to check it out I tried it on some random nick..and surprisingly it worked on the other nick...Unfortunately I still have no idea what caused it

**Comment by Draecal** [comment]
After updating, it just doesn't work and sometimes the player starts flying and can go trough any block

**Comment by Syrent** [comment]
Hey, let’s tackle one issue at a time. Could you send me the output key of `/sayanvanish paste`? For now, let’s focus on the `fake_message` feature issue.

**Comment by HonzasikCZ** [comment]
https://pastes.dev/PRErxHRjlI

**Comment by HonzasikCZ** [comment]
I have both enabled and it's still not working

state:
```
remember: true
vanish-on-join: false
reappear-on-quit: false
check-permission-on-quit: true
check-permission-on-join: true
id: state
enabled: true
```
level:
```
see-as-spectator: true
level-method: PERMISSION
id: level
enabled: true
```

**Comment by Syrent** [comment]
if possible, could you share your server address so I can join and take a closer look at the issue? Please feel free to message me on Discord (my id: `.syrent`).

**Comment by Syrent** [comment]
Fixed, update plugin to latest snapshot and make sure to enable `check-permission-via-luckperms` option in `hook_luckperms.yml` feature
