### ISSUE TITLE
PLAYERS IN MOTD

### ISSUE THREAD

**Issue by HonzasikCZ** [Syrent/SayanVanish#354]
Hello!

I noticed that the motd doesn't show players who have permisions to vanish (Players don't have vanish turned on they just have permissions)

I use the plugin: MiniMOTD https://www.spigotmc.org/resources/minimotd-server-list-motd-plugin-with-rgb-gradients.81254/

I don't know if I should post it here or on the MiniMOTD github

**Comment by Syrent** [comment]
Hey, which platform do you use MiniMOTD on? and is it for the player list hover or just the online count?

**Comment by HonzasikCZ** [comment]
Purpur

I'm sure the online count but unfortunately now I can't test the player list hover since there are 20 players on the server but I think it didn't show on that either

**Comment by Syrent** [comment]
Try this build: https://hangar.papermc.io/Syrent/SayanVanish/versions/1.6.1-SNAPSHOT-build.217

**Comment by HonzasikCZ** [comment]
Yes it works! Thank you very much!
